### ISSUE TITLE
Can you show your xrb donationg address?

### ISSUE THREAD

**Issue by osdio** [brainblocks/brainblocks-ios-sdk#1]

**Comment by schenkty** [comment]
I have updated the readme with the donate address. Here they are also. 

Donate to schenkty (myself): xrb_1jnatu97dka1h49zudxtpxxrho3j591jwu5bzsn7h1kzn3gwit4kejak756y 

Donate to BrainBlocks: xrb_164xaa1ojy6qmq9e8t94mz8izr4mkf1sojb6xrmstru5jsif48g5kegcqg7y

**Comment by osdio** [comment]
Have donated 50xrb, txId: https://raiblocks.net/block/index.php?h=7C5C6F0BCE80460B5BCC885CF2AF0E7EF9CF4ABB50F4A7ABE97573BF8BAECFFF

**Comment by schenkty** [comment]
Thank you! I really appreciate it
