### ISSUE TITLE
Tap on address to copy

### ISSUE THREAD

**Issue by Lorenzo45** [brainblocks/brainblocks-ios-sdk#2]
I think a useful feature to add would be the ability to copy the address by simply tapping on it. This would allow for easier payments once we get a raiblocks app or if the user wants to send the address to another person/device. Some sort of icon to make it obvious that you can do this (along with some feedback to say that it has been copied to the clipboard) would be useful as well!

**Comment by schenkty** [comment]
Great Idea! I will work on adding this in. Thanks for the suggestion.

**Comment by schenkty** [comment]
This now works. Tap on the QR code to copy to clipboard!

**Comment by Lorenzo45** [comment]
Thanks! Glad you liked the suggestion! Keep up the great work!
