### ISSUE TITLE
Unsupported Swift Version

### ISSUE THREAD

**Issue by brianfoody** [brainblocks/brainblocks-ios-sdk#4]
Hi @schenkty. Apologies first off as my working knowledge of CocoaPods is very basic so probably something simple I'm doing wrong here.

Working on React Native library and when I do a pod install and open up the .xcworkspace in XCode9 I am presented with this error. Do you have any advice on the best way to resolve?

<img width="419" alt="screen shot 2018-01-28 at 12 02 26 pm" src="https://user-images.githubusercontent.com/1926757/35478852-4e8b66a4-0423-11e8-9563-267b1b917ac0.png">

**Comment by schenkty** [comment]
Can you please show me the podfile?

**Comment by brianfoody** [comment]
As per instructions

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'RNBrainBlocks' do
  pod 'BrainBlocksKit'
end
```

**Comment by schenkty** [comment]
Alright just checking. I should not be using any swift 2.0 code at all so that's why I wondered. one second let me look into this. I build with Xcode 9 so its very odd

**Comment by brianfoody** [comment]
Very strange alright. Perhaps something to do with React Native.

These were the steps I took.
```
react-native init RNBrainBlocks
cd RNBrainBlocks/ios
pod init
nano Podfile
```

[enter above]

```
pod install
```

From there opening .xcworkspace gives the above error.

**Comment by schenkty** [comment]
thanks for the steps. let me set this up on my mac and see what I get. should not take too long 👍

**Comment by brianfoody** [comment]
Okay so I've isolated the problem to not be an issue with React Native per-se but just the fact that React Native creates an Objective-C project. If you create a simple single page app as per screenshot and integrate the library it will replicate.

<img width="737" alt="screen shot 2018-01-28 at 12 15 35 pm" src="https://user-images.githubusercontent.com/1926757/35478947-669fe79a-0425-11e8-80ee-086e0f4c2e0b.png">

**Comment by schenkty** [comment]
Yeah, the issue is that our SDK is built with swift so when you include it in the Obj-C project - it does not know what to do. I would suggest maybe adding the SDK to the react project using the bridge method. It would not be as clean but should work. Here are the details on mixing swift and Objective-C: https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by brianfoody** [comment]
Thanks @schenkty . Spot on. This solution here seems to have done the job.

https://github.com/Alamofire/Alamofire/issues/1526

I have changed the Podfile here and it builds now. I will close the issue and add instructions to the readme for the react-native library.

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ObjectiveCBrainBlocks' do
  pod 'BrainBlocksKit'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
  end
```

**Comment by brianfoody** [comment]
Thanks for the quick feedback mate, really appreciated.

**Comment by schenkty** [comment]
No worries. You fixed the issue faster than me though 👍

**Comment by brianfoody** [comment]
Ha, felt guilty about you going off doing work when I hadn't done the proper research myself.
